### ISSUE TITLE
Great tool

### ISSUE THREAD

**Issue by SolomonSklash** [root4loot/rescope#1]
Just wanted to say that this is a great tool, and I have integrated it into my tool [Chomp Scan](https://github.com/SolomonSklash/chomp-scan). Thanks for your work on this.

**Comment by root4loot** [comment]
The honor is mine, appreciate the positive feedback!  Your tool looks great also, I'll be sure to check it out 👍

**Comment by root4loot** [comment]
I'll leave this open in case someone wants to jump in. Anything goes
