### ISSUE TITLE
Error parsing bugcrowd

### ISSUE THREAD

**Issue by mr0xE** [root4loot/rescope#11]
There seems to be an error when parsing Bugcrowd programs.
![Untitled](https://user-images.githubusercontent.com/84565972/142597072-cbfd3184-324b-40b2-a14b-c3ba2216b16d.png)

As compared to hackerone programs.
![Untitled](https://user-images.githubusercontent.com/84565972/142597744-0cb21411-3b22-4aa8-8fa2-923c1e50ee45.png)

Am using version 2.2

**Comment by root4loot** [comment]
Thank you for reporting this and sorry for the late response. 
Issue is caused by changes in bugcrowd app/layout, which 77d2afb should resolve.
Can you confirm this? Update with the following command:

```
go install github.com/root4loot/rescope@latest
```
