### ISSUE TITLE
Omits capital letters in input file

### ISSUE THREAD

**Issue by soaringswine** [root4loot/rescope#6]
If I have an input file containing something like "Openwebsite.com", the Burp output file will contain:
`{
  "target": {
    "scope": {
      "advanced_mode": true,
      "exclude": null,
      "include": [
        {
          "enabled": true,
          "file": "^[\\S]*$",
          "host": "^penwebsite\\.com$",
          "port": "^(80|443)$",
          "protocol": "Any"
        }
      ]
    }
  }
}#`

and thus "Openwebsite.com" will not be considered in-scope in Burp.

**Comment by root4loot** [comment]
Thanks for reporting this, and sorry for the late reply here.

I found that domains having leading upper-case are often part of a sentence, so I deliberately did this to filter those out. However, this is not clear from the documentation, and I reckon it is not an ideal approach. Having said that, I've decided to remove the case-sensitive check, so this should no longer be a problem.

To confirm, run `go get -u github.com/root4loot/rescope` to update and try again. Thanks!
